version: '3'

services:
    # ingest - listening on port 8084
    lightspeed-ingest:     
        restart: on-failure
        image: projectlightspeed/ingest:version-0.1.1
        network_mode: host
        ports:
            - "8084:8084"
    
    # react - serves on port 80, needs the wsUrl which is public ip:8080
    lightspeed-react:    
        restart: on-failure
        image: projectlightspeed/react:version-0.1.0
        network_mode: host
        ports:
            - "80:80"
        volumes: 
            - ./config.json:/usr/share/nginx/html/config.json

    # webrtc, defaults to localhost:8080. 
    lightspeed-webrtc:     
        restart: on-failure
        image: projectlightspeed/webrtc:version-0.1.0
        network_mode: host
        command: ["lightspeed-webrtc", "--addr=localhost"]
        ports:
            - "8080:8080"
            - "65535:65535/udp"